const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chao: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{varão: 0},
	{esquerdo: 0},
	{direito: 0},
	{jump: 0},
	{Toque: 0},
	{plataforma: 0},
	{caixa: 0},
	{portalDeEntrada: 0},
	{portaDesaida: 0},
	{Sprite5: 0},
	{LImites: 0},
	{particulaCaixa: 0},
	{chave: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Senóide: 0},
	{inimigo: 0},
	{Partículas: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{play: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{txtchaves: 0},
	{vidas: 0},
	{txtvidas: 0},
	{Sprite10: 0},
	{Áudio: 0},
	{estado: 0},
	{achouchave: 0}
];

self.InstanceType = {
	chao: class extends self.ITiledBackgroundInstance {},
	varão: class extends self.ISpriteInstance {},
	esquerdo: class extends self.ISpriteInstance {},
	direito: class extends self.ISpriteInstance {},
	jump: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	plataforma: class extends self.ITiledBackgroundInstance {},
	caixa: class extends self.ISpriteInstance {},
	portalDeEntrada: class extends self.ISpriteInstance {},
	portaDesaida: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	LImites: class extends self.ISpriteInstance {},
	particulaCaixa: class extends self.IParticlesInstance {},
	chave: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	txtchaves: class extends self.ITextInstance {},
	vidas: class extends self.ISpriteInstance {},
	txtvidas: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}